# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/?(*.ear|*.war|*.jar)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: Veracode@3
  displayName: SAST Scan
  enabled: false
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: '30268-VerademoJava'
    veracodeAppProfile: '$(Application_Profile_name)'
    version: 'Verademo-$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    createSandBox: false # Set true to create sandbox, or false if sandbox is already created
    sandboxName: 'Verademo'
    # importResults: true # Set true if you want the SAST scan results in the console output
    maximumWaitTime: '360'

- task: CmdLine@2
  displayName: SCA Scan 
  enabled: true
  inputs:
    script: |
      export SCM_URI='https://$(Application_Profile_name)'
      export SRCCLR_API_TOKEN=$(SRCCLR_API_TOKEN)
      export scaDownloadUrl=https://download.srcclr.com/ci.sh
      export SCM_REF_TYPE=branch
      # make sure the branch name is set appropriately for the below scm_ref 
      export SCM_REF=main
      export SCM_REV=1.0
      # If the pom file is not in source directory cd to where pom.xml and add the maven settings to the scan run
      # cd $(Build.SourcesDirectory)/$(repo_name)
      # ls -ld  ~/.m2
      # cp $(Build.SourcesDirectory)/maven-settings.xml ~/.m2/settings.xml
      # ls -l  ~/.m2/settings.xml
      # curl -sSL $scaDownloadUrl | env DEBUG=1 bash -s scan --scm-uri $SCM_URI --scm-rev $SCM_REV --scm-ref $SCM_REF --scm-ref-type $SCM_REF_TYPE
      curl -X 'GET' \
      'https://api.veracode.com/srcclr/v3/workspaces?filter%5Bworkspace%5D=WS-30268' \
      -H 'accept: application/json'