name: SCA Agent-Based Scan Action
on: 
  workflow_dispatch:

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: SCA Agent-Based Scan
    env:
      SRCCLR_SCM_TYPE: "GITHUB"
      SRCCLR_SCM_TOKEN: ${{ secrets.SRCCLR_SCM_TOKEN }}
      SRCCLR_PR_ON: "low"
      SRCCLR_NO_BREAKING_UPDATES: true
      SRCCLR_IGNORE_CLOSED_PRS: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.10
        with:
          create-issues: false
          update_advisor: true
          debug: true
          run: |
            git config --global user.email "thomas.saekao@gmail.com"
            git config --global user.name "Thomas Saekao"
