name: SCA Agent-Based Scan PR
on: 
  workflow_dispatch:
  pull_request:

permissions: write-all

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: SCA Agent-Based Scan
    env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRCCLR_SCM_TYPE: 'GITHUB'
          SRCCLR_SCM_TOKEN: "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"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: SCA Agent Scan
        run: |
             export SRCCLR_SCM_TYPE='GITHUB'
             export SRCCLR_SCM_TOKEN="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"

             export SRCCLR_PR_ON='low'
             export SRCCLR_ENABLE_PR=true
             export SRCCLR_NO_BREAKING_UPDATES=false
             export SRCCLR_IGNORE_CLOSED_PRS=true

             export SRCCLR_API_TOKEN=${{ secrets.SRCCLR_API_TOKEN }}
             curl -sSL https://download.sourceclear.com/ci.sh | bash -s - scan --update-advisor --allow-dirty --recursive --pull-request

#              export SRCCLR_SCM_URL='https://github.com/tsaekao/verademo-java/tree/PR'
